repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-shebang-scripts-are-executable
    -   id: pretty-format-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    # -   id: no-commit-to-branch
    # args: [--branch, main, --branch, master]
    -   id: trailing-whitespace
